# Generated by Django 3.1.2 on 2020-10-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20200811_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
